Collections:
- Metadata:
    Architecture:
    - HRNet
  Name: hrnet_h36m
  Paper:
  - http://openaccess.thecvf.com/content_CVPR_2019/html/Sun_Deep_High-Resolution_Representation_Learning_for_Human_Pose_Estimation_CVPR_2019_paper.html
  - https://ieeexplore.ieee.org/abstract/document/6682899/
  README: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/h36m/hrnet_h36m.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/h36m/hrnet_w32_h36m_256x256.py
  In Collection: hrnet_h36m
  Metadata:
    Training Data: Human3.6M
  Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--h36m--hrnet_w32_h36m_256x256
  Results:
  - Dataset: Human3.6M
    Metrics:
      EPE: 9.43
      PCK: 0.911
    Task: Image-based Human Body 2D Pose Estimation
  Weights: https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w32_h36m_256x256-d3206675_20210621.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/h36m/hrnet_w48_h36m_256x256.py
  In Collection: hrnet_h36m
  Metadata:
    Training Data: Human3.6M
  Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--h36m--hrnet_w48_h36m_256x256
  Results:
  - Dataset: Human3.6M
    Metrics:
      EPE: 7.36
      PCK: 0.932
    Task: Image-based Human Body 2D Pose Estimation
  Weights: https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w48_h36m_256x256-78e88d08_20210621.pth
