Collections:
- Metadata:
    Architecture:
    - SimpleBaseline3D
  Name: simplebaseline3d_mpi-inf-3dhp
  Paper:
  - http://openaccess.thecvf.com/content_iccv_2017/html/Martinez_A_Simple_yet_ICCV_2017_paper.html
  - https://ieeexplore.ieee.org/abstract/document/8374605/
  README: configs/body/3d_kpt_sview_rgb_img/pose_lift/mpi_inf_3dhp/simplebaseline3d_mpi-inf-3dhp.md
Models:
- Config: configs/body/3d_kpt_sview_rgb_img/pose_lift/mpi_inf_3dhp/simplebaseline3d_mpi-inf-3dhp.py
  In Collection: simplebaseline3d_mpi-inf-3dhp
  Metadata:
    Training Data: MPI-INF-3DHP
  Name: body--3d_kpt_sview_rgb_img--pose_lift--mpi_inf_3dhp--simplebaseline3d_mpi-inf-3dhp
  Results:
  - Dataset: MPI-INF-3DHP
    Metrics:
      3DAUC: 52.0
      3DPCK: 85.0
      MPJPE: 84.3
      P-MPJPE: 53.2
    Task: Single-view 3D Human Body Pose Estimation
  Weights: https://download.openmmlab.com/mmpose/body3d/simplebaseline3d/simplebaseline3d_mpi-inf-3dhp-b75546f6_20210603.pth
