Collections:
- Metadata:
    Architecture:
    - SimpleBaseline2D
    - ResNet
  Name: resnet_panoptic2d
  Paper:
  - http://openaccess.thecvf.com/content_ECCV_2018/html/Bin_Xiao_Simple_Baselines_for_ECCV_2018_paper.html
  - http://openaccess.thecvf.com/content_cvpr_2016/html/He_Deep_Residual_Learning_CVPR_2016_paper.html
  - http://openaccess.thecvf.com/content_cvpr_2017/html/Simon_Hand_Keypoint_Detection_CVPR_2017_paper.html
  README: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/panoptic2d/resnet_panoptic2d.md
Models:
- Config: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/panoptic2d/res50_panoptic_256x256.py
  In Collection: resnet_panoptic2d
  Metadata:
    Training Data: CMU Panoptic HandDB
  Name: hand--2d_kpt_sview_rgb_img--topdown_heatmap--panoptic2d--res50_panoptic_256x256
  Results:
  - Dataset: CMU Panoptic HandDB
    Metrics:
      AUC: 0.713
      EPE: 9.0
      PCKh@0.7: 0.999
    Task: 2D Hand Pose Estimation
  Weights: https://download.openmmlab.com/mmpose/hand/resnet/res50_panoptic_256x256-4eafc561_20210330.pth
