Collections:
- Metadata:
    Architecture:
    - MobilenetV2
  Name: mobilenetv2_rhd2d
  Paper:
  - http://openaccess.thecvf.com/content_cvpr_2018/html/Sandler_MobileNetV2_Inverted_Residuals_CVPR_2018_paper.html
  - https://lmb.informatik.uni-freiburg.de/projects/hand3d/
  README: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/rhd2d/mobilenetv2_rhd2d.md
Models:
- Config: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/rhd2d/mobilenetv2_rhd2d_256x256.py
  In Collection: mobilenetv2_rhd2d
  Metadata:
    Training Data: RHD
  Name: hand--2d_kpt_sview_rgb_img--topdown_heatmap--rhd2d--mobilenetv2_rhd2d_256x256
  Results:
  - Dataset: RHD
    Metrics:
      AUC: 0.883
      EPE: 2.8
      PCK@0.2: 0.985
    Task: 2D Hand Pose Estimation
  Weights: https://download.openmmlab.com/mmpose/hand/mobilenetv2/mobilenetv2_rhd2d_256x256-85fa02db_20210330.pth
