Collections:
- Metadata:
    Architecture:
    - SimpleBaseline2D
    - ResNet
  Name: resnet_rhd2d
  Paper:
  - http://openaccess.thecvf.com/content_ECCV_2018/html/Bin_Xiao_Simple_Baselines_for_ECCV_2018_paper.html
  - http://openaccess.thecvf.com/content_cvpr_2016/html/He_Deep_Residual_Learning_CVPR_2016_paper.html
  - https://lmb.informatik.uni-freiburg.de/projects/hand3d/
  README: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/rhd2d/resnet_rhd2d.md
Models:
- Config: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/rhd2d/hrnetv2_w18_rhd2d_256x256_udp.py
  In Collection: resnet_rhd2d
  Metadata:
    Training Data: RHD
  Name: hand--2d_kpt_sview_rgb_img--topdown_heatmap--rhd2d--hrnetv2_w18_rhd2d_256x256_udp
  Results:
  - Dataset: RHD
    Metrics:
      AUC: 0.902
      EPE: 2.21
      PCK@0.2: 0.992
    Task: 2D Hand Pose Estimation
  Weights: https://download.openmmlab.com/mmpose/hand/udp/hrnetv2_w18_rhd2d_256x256_udp-63ba6007_20210330.pth
