Collections:
- Metadata:
    Architecture:
    - HRNet
  Name: hrnet_crowdpose
  Paper:
  - http://openaccess.thecvf.com/content_CVPR_2019/html/Sun_Deep_High-Resolution_Representation_Learning_for_Human_Pose_Estimation_CVPR_2019_paper.html
  - http://openaccess.thecvf.com/content_CVPR_2019/html/Li_CrowdPose_Efficient_Crowded_Scenes_Pose_Estimation_and_a_New_Benchmark_CVPR_2019_paper.html
  README: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/crowdpose/hrnet_crowdpose.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/crowdpose/hrnet_w32_crowdpose_256x192.py
  In Collection: hrnet_crowdpose
  Metadata:
    Training Data: CrowdPose
  Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--crowdpose--hrnet_w32_crowdpose_256x192
  Results:
  - Dataset: CrowdPose
    Metrics:
      AP: 0.675
      AP (E): 0.77
      AP (H): 0.553
      AP (M): 0.687
      AP@0.5: 0.825
      AP@0.75: 0.729
    Task: Image-based Human Body 2D Pose Estimation
  Weights: https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w32_crowdpose_256x192-960be101_20201227.pth
