Collections:
- Metadata:
    Architecture:
    - SimpleBaseline2D
    - ResNet
  Name: resnet_deepfashion
  Paper:
  - http://openaccess.thecvf.com/content_ECCV_2018/html/Bin_Xiao_Simple_Baselines_for_ECCV_2018_paper.html
  - http://openaccess.thecvf.com/content_cvpr_2016/html/He_Deep_Residual_Learning_CVPR_2016_paper.html
  - http://openaccess.thecvf.com/content_cvpr_2016/html/Liu_DeepFashion_Powering_Robust_CVPR_2016_paper.html
  - https://link.springer.com/chapter/10.1007/978-3-319-46475-6_15
  README: configs/fashion/2d_kpt_sview_rgb_img/topdown_heatmap/deepfashion/resnet_deepfashion.md
Models:
- Config: configs/fashion/2d_kpt_sview_rgb_img/topdown_heatmap/deepfashion/res50_deepfashion_upper_256x192.py
  In Collection: resnet_deepfashion
  Metadata:
    Training Data: DeepFashion
  Name: fashion--2d_kpt_sview_rgb_img--topdown_heatmap--deepfashion--res50_deepfashion_upper_256x192
  Results:
  - Dataset: DeepFashion
    Metrics:
      AUC: 0.578
      EPE: 16.8
      PCK@0.2: 0.954
    Task: 2D Fashion Landmark Detection
  Weights: https://download.openmmlab.com/mmpose/fashion/resnet/res50_deepfashion_upper_256x192-41794f03_20210124.pth
- Config: configs/fashion/2d_kpt_sview_rgb_img/topdown_heatmap/deepfashion/res50_deepfashion_lower_256x192.py
  In Collection: resnet_deepfashion
  Metadata:
    Training Data: DeepFashion
  Name: fashion--2d_kpt_sview_rgb_img--topdown_heatmap--deepfashion--res50_deepfashion_lower_256x192
  Results:
  - Dataset: DeepFashion
    Metrics:
      AUC: 0.744
      EPE: 10.5
      PCK@0.2: 0.965
    Task: 2D Fashion Landmark Detection
  Weights: https://download.openmmlab.com/mmpose/fashion/resnet/res50_deepfashion_lower_256x192-1292a839_20210124.pth
- Config: configs/fashion/2d_kpt_sview_rgb_img/topdown_heatmap/deepfashion/res50_deepfashion_full_256x192.py
  In Collection: resnet_deepfashion
  Metadata:
    Training Data: DeepFashion
  Name: fashion--2d_kpt_sview_rgb_img--topdown_heatmap--deepfashion--res50_deepfashion_full_256x192
  Results:
  - Dataset: DeepFashion
    Metrics:
      AUC: 0.664
      EPE: 12.7
      PCK@0.2: 0.977
    Task: 2D Fashion Landmark Detection
  Weights: https://download.openmmlab.com/mmpose/fashion/resnet/res50_deepfashion_full_256x192-0dbd6e42_20210124.pth
