Collections:
- Metadata:
    Architecture:
    - AlexNet
  Name: alexnet_coco
  Paper:
  - https://proceedings.neurips.cc/paper/4824-imagenet-classification-with-deep-convolutional-neural-networks.pdf
  - https://link.springer.com/chapter/10.1007/978-3-319-10602-1_48
  README: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/alexnet_coco.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/alexnet_coco_256x192.py
  In Collection: alexnet_coco
  Metadata:
    Training Data: COCO
  Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--coco--alexnet_coco_256x192
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.397
      AP@0.5: 0.758
      AP@0.75: 0.381
      AR: 0.478
      AR@0.5: 0.822
    Task: Image-based Human Body 2D Pose Estimation
  Weights: https://download.openmmlab.com/mmpose/top_down/alexnet/alexnet_coco_256x192-a7b1fd15_20200727.pth
