Collections:
- Metadata:
    Architecture:
    - HRNet
  Name: hrnet_fp16_coco
  Paper:
  - http://openaccess.thecvf.com/content_CVPR_2019/html/Sun_Deep_High-Resolution_Representation_Learning_for_Human_Pose_Estimation_CVPR_2019_paper.html
  - https://arxiv.org/abs/1710.03740
  - https://link.springer.com/chapter/10.1007/978-3-319-10602-1_48
  README: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_fp16_coco.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_w32_coco_256x192_fp16_dynamic.py
  In Collection: hrnet_fp16_coco
  Metadata:
    Training Data: COCO
  Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--coco--hrnet_w32_coco_256x192_fp16_dynamic
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.746
      AP@0.5: 0.905
      AP@0.75: 0.88
      AR: 0.8
      AR@0.5: 0.943
    Task: Image-based Human Body 2D Pose Estimation
  Weights: hrnet_w32_coco_256x192_fp16_dynamic-290efc2e_20210430.pth
