Collections:
- Metadata:
    Architecture:
    - MSPN
  Name: mspn_coco
  Paper:
  - https://arxiv.org/abs/1901.00148
  - https://link.springer.com/chapter/10.1007/978-3-319-10602-1_48
  README: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/mspn_coco.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/mspn50_coco_256x192.py
  In Collection: mspn_coco
  Metadata:
    Training Data: COCO
  Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--coco--mspn50_coco_256x192
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.723
      AP@0.5: 0.895
      AP@0.75: 0.794
      AR: 0.788
      AR@0.5: 0.933
    Task: Image-based Human Body 2D Pose Estimation
  Weights: https://download.openmmlab.com/mmpose/top_down/mspn/mspn50_coco_256x192-8fbfb5d0_20201123.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/2xmspn50_coco_256x192.py
  In Collection: mspn_coco
  Metadata:
    Training Data: COCO
  Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--coco--2xmspn50_coco_256x192
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.754
      AP@0.5: 0.903
      AP@0.75: 0.825
      AR: 0.815
      AR@0.5: 0.941
    Task: Image-based Human Body 2D Pose Estimation
  Weights: https://download.openmmlab.com/mmpose/top_down/mspn/2xmspn50_coco_256x192-c8765a5c_20201123.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/3xmspn50_coco_256x192.py
  In Collection: mspn_coco
  Metadata:
    Training Data: COCO
  Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--coco--3xmspn50_coco_256x192
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.758
      AP@0.5: 0.904
      AP@0.75: 0.83
      AR: 0.821
      AR@0.5: 0.943
    Task: Image-based Human Body 2D Pose Estimation
  Weights: https://download.openmmlab.com/mmpose/top_down/mspn/3xmspn50_coco_256x192-e348f18e_20201123.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/4xmspn50_coco_256x192.py
  In Collection: mspn_coco
  Metadata:
    Training Data: COCO
  Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--coco--4xmspn50_coco_256x192
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.764
      AP@0.5: 0.906
      AP@0.75: 0.835
      AR: 0.826
      AR@0.5: 0.944
    Task: Image-based Human Body 2D Pose Estimation
  Weights: https://download.openmmlab.com/mmpose/top_down/mspn/4xmspn50_coco_256x192-7b837afb_20201123.pth
