Collections:
- Metadata:
    Architecture:
    - SimpleBaseline2D
    - ResNet
  Name: resnet_freihand2d
  Paper:
  - http://openaccess.thecvf.com/content_ECCV_2018/html/Bin_Xiao_Simple_Baselines_for_ECCV_2018_paper.html
  - http://openaccess.thecvf.com/content_cvpr_2016/html/He_Deep_Residual_Learning_CVPR_2016_paper.html
  - http://openaccess.thecvf.com/content_ICCV_2019/html/Zimmermann_FreiHAND_A_Dataset_for_Markerless_Capture_of_Hand_Pose_and_ICCV_2019_paper.html
  README: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/freihand2d/resnet_freihand2d.md
Models:
- Config: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/freihand2d/res50_freihand_224x224.py
  In Collection: resnet_freihand2d
  Metadata:
    Training Data: FreiHand
  Name: hand--2d_kpt_sview_rgb_img--topdown_heatmap--freihand2d--res50_freihand_224x224
  Results:
  - Dataset: FreiHand
    Metrics:
      AUC: 0.868
      EPE: 3.25
      PCK@0.2: 0.993
    Task: 2D Hand Pose Estimation
  Weights: https://download.openmmlab.com/mmpose/hand/resnet/res50_freihand_224x224-ff0799bc_20200914.pth
- Config: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/freihand2d/res50_freihand_224x224.py
  In Collection: resnet_freihand2d
  Metadata:
    Training Data: FreiHand
  Name: hand--2d_kpt_sview_rgb_img--topdown_heatmap--freihand2d--res50_freihand_224x224
  Results:
  - Dataset: FreiHand
    Metrics:
      AUC: 0.868
      EPE: 3.27
      PCK@0.2: 0.992
    Task: 2D Hand Pose Estimation
  Weights: https://download.openmmlab.com/mmpose/hand/resnet/res50_freihand_224x224-ff0799bc_20200914.pth
