Collections:
- Metadata:
    Architecture:
    - HRNetv2
  Name: hrnetv2_300w
  Paper:
  - https://ieeexplore.ieee.org/abstract/document/9052469/
  - https://www.sciencedirect.com/science/article/pii/S0262885616000147
  README: configs/face/2d_kpt_sview_rgb_img/topdown_heatmap/300w/hrnetv2_300w.md
Models: []
