Collections:
- Metadata:
    Architecture:
    - HRNetv2
  Name: hrnetv2_aflw
  Paper:
  - https://ieeexplore.ieee.org/abstract/document/9052469/
  - https://ieeexplore.ieee.org/abstract/document/6130513/
  README: configs/face/2d_kpt_sview_rgb_img/topdown_heatmap/aflw/hrnetv2_aflw.md
Models:
- Config: configs/face/2d_kpt_sview_rgb_img/topdown_heatmap/aflw/hrnetv2_w18_aflw_256x256.py
  In Collection: hrnetv2_aflw
  Metadata:
    Training Data: AFLW
  Name: face--2d_kpt_sview_rgb_img--topdown_heatmap--aflw--hrnetv2_w18_aflw_256x256
  Results:
  - Dataset: AFLW
    Metrics:
      NME frontal: 1.27
      NME full: 1.41
    Task: 2D Face Landmark Detection
  Weights: https://download.openmmlab.com/mmpose/face/hrnetv2/hrnetv2_w18_aflw_256x256-f2bbc62b_20210125.pth
