Collections:
- Metadata:
    Architecture:
    - SimpleBaseline2D
  Name: resnet_zebra
  Paper:
  - http://openaccess.thecvf.com/content_ECCV_2018/html/Bin_Xiao_Simple_Baselines_for_ECCV_2018_paper.html
  - https://elifesciences.org/articles/47994
  README: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/zebra/resnet_zebra.md
Models:
- Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/zebra/res50_zebra_160x160.py
  In Collection: resnet_zebra
  Metadata:
    Training Data: "Gr\xE9vy\u2019s Zebra"
  Name: animal--2d_kpt_sview_rgb_img--topdown_heatmap--zebra--res50_zebra_160x160
  Results:
  - Dataset: "Gr\xE9vy\u2019s Zebra"
    Metrics:
      AUC: 0.914
      EPE: 1.86
      PCK@0.2: 1.0
    Task: 2D Animal Keypoint Detection
  Weights: https://download.openmmlab.com/mmpose/animal/resnet/res50_zebra_160x160-5a104833_20210407.pth
- Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/zebra/res101_zebra_160x160.py
  In Collection: resnet_zebra
  Metadata:
    Training Data: "Gr\xE9vy\u2019s Zebra"
  Name: animal--2d_kpt_sview_rgb_img--topdown_heatmap--zebra--res101_zebra_160x160
  Results:
  - Dataset: "Gr\xE9vy\u2019s Zebra"
    Metrics:
      AUC: 0.916
      EPE: 1.82
      PCK@0.2: 1.0
    Task: 2D Animal Keypoint Detection
  Weights: https://download.openmmlab.com/mmpose/animal/resnet/res101_zebra_160x160-e8cb2010_20210407.pth
- Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/zebra/res152_zebra_160x160.py
  In Collection: resnet_zebra
  Metadata:
    Training Data: "Gr\xE9vy\u2019s Zebra"
  Name: animal--2d_kpt_sview_rgb_img--topdown_heatmap--zebra--res152_zebra_160x160
  Results:
  - Dataset: "Gr\xE9vy\u2019s Zebra"
    Metrics:
      AUC: 0.921
      EPE: 1.66
      PCK@0.2: 1.0
    Task: 2D Animal Keypoint Detection
  Weights: https://download.openmmlab.com/mmpose/animal/resnet/res152_zebra_160x160-05de71dd_20210407.pth
