Collections:
- Metadata:
    Architecture:
    - SimpleBaseline2D
  Name: resnet_macaque
  Paper:
  - http://openaccess.thecvf.com/content_ECCV_2018/html/Bin_Xiao_Simple_Baselines_for_ECCV_2018_paper.html
  - https://www.ncbi.nlm.nih.gov/pmc/articles/pmc7874091/
  README: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/macaque/resnet_macaque.md
Models:
- Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/macaque/res50_macaque_256x192.py
  In Collection: resnet_macaque
  Metadata:
    Training Data: MacaquePose
  Name: animal--2d_kpt_sview_rgb_img--topdown_heatmap--macaque--res50_macaque_256x192
  Results:
  - Dataset: MacaquePose
    Metrics:
      AP: 0.799
      AP@0.5: 0.952
      AP@0.75: 0.919
      AR: 0.837
      AR@0.5: 0.964
    Task: 2D Animal Keypoint Detection
  Weights: https://download.openmmlab.com/mmpose/animal/resnet/res50_macaque_256x192-98f1dd3a_20210407.pth
- Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/macaque/res101_macaque_256x192.py
  In Collection: resnet_macaque
  Metadata:
    Training Data: MacaquePose
  Name: animal--2d_kpt_sview_rgb_img--topdown_heatmap--macaque--res101_macaque_256x192
  Results:
  - Dataset: MacaquePose
    Metrics:
      AP: 0.79
      AP@0.5: 0.953
      AP@0.75: 0.908
      AR: 0.828
      AR@0.5: 0.967
    Task: 2D Animal Keypoint Detection
  Weights: https://download.openmmlab.com/mmpose/animal/resnet/res101_macaque_256x192-e3b9c6bb_20210407.pth
- Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/macaque/res152_macaque_256x192.py
  In Collection: resnet_macaque
  Metadata:
    Training Data: MacaquePose
  Name: animal--2d_kpt_sview_rgb_img--topdown_heatmap--macaque--res152_macaque_256x192
  Results:
  - Dataset: MacaquePose
    Metrics:
      AP: 0.794
      AP@0.5: 0.951
      AP@0.75: 0.915
      AR: 0.834
      AR@0.5: 0.968
    Task: 2D Animal Keypoint Detection
  Weights: https://download.openmmlab.com/mmpose/animal/resnet/res152_macaque_256x192-c42abc02_20210407.pth
