Collections:
- Metadata:
    Architecture:
    - DeepPose
    - ResNet
  Name: resnet_onehand10k
  Paper:
  - http://openaccess.thecvf.com/content_cvpr_2014/html/Toshev_DeepPose_Human_Pose_2014_CVPR_paper.html
  - http://openaccess.thecvf.com/content_cvpr_2016/html/He_Deep_Residual_Learning_CVPR_2016_paper.html
  - https://ieeexplore.ieee.org/abstract/document/8529221/
  README: configs/hand/2d_kpt_sview_rgb_img/deeppose/onehand10k/resnet_onehand10k.md
Models:
- Config: configs/hand/2d_kpt_sview_rgb_img/deeppose/onehand10k/res50_onehand10k_256x256.py
  In Collection: resnet_onehand10k
  Metadata:
    Training Data: OneHand10K
  Name: hand--2d_kpt_sview_rgb_img--deeppose--onehand10k--res50_onehand10k_256x256
  Results:
  - Dataset: OneHand10K
    Metrics:
      AUC: 0.486
      EPE: 34.28
      PCK@0.2: 0.99
    Task: 2D Hand Pose Estimation
  Weights: https://download.openmmlab.com/mmpose/hand/deeppose/deeppose_res50_onehand10k_256x256-cbddf43a_20210330.pth
