Collections:
- Metadata:
    Architecture:
    - DeepPose
    - ResNet
    - Wingloss
  Name: resnet_wingloss_wflw
  Paper:
  - http://openaccess.thecvf.com/content_cvpr_2014/html/Toshev_DeepPose_Human_Pose_2014_CVPR_paper.html
  - http://openaccess.thecvf.com/content_cvpr_2016/html/He_Deep_Residual_Learning_CVPR_2016_paper.html
  - http://openaccess.thecvf.com/content_cvpr_2018/html/Feng_Wing_Loss_for_CVPR_2018_paper.html
  - http://openaccess.thecvf.com/content_cvpr_2018/html/Wu_Look_at_Boundary_CVPR_2018_paper.html
  README: configs/face/2d_kpt_sview_rgb_img/deeppose/wflw/resnet_wingloss_wflw.md
Models:
- Config: configs/face/2d_kpt_sview_rgb_img/deeppose/wflw/res50_wflw_256x256_wingloss.py
  In Collection: resnet_wingloss_wflw
  Metadata:
    Training Data: WFLW
  Name: face--2d_kpt_sview_rgb_img--deeppose--wflw--res50_wflw_256x256_wingloss
  Results:
  - Dataset: WFLW
    Metrics:
      NME blur: 5.26
      NME expression: 5.07
      NME illumination: 4.59
      NME makeup: 4.59
      NME occlusion: 5.56
      NME pose: 8.25
      NME test: 4.64
    Task: 2D Face Landmark Detection
  Weights: https://download.openmmlab.com/mmpose/face/deeppose/deeppose_res50_wflw_256x256_wingloss-f82a5e53_20210303.pth
