Collections:
- Metadata:
    Architecture:
    - ShufflenetV2
  Name: shufflenetv2_mpii
  Paper:
  - http://openaccess.thecvf.com/content_ECCV_2018/html/Ningning_Light-weight_CNN_Architecture_ECCV_2018_paper.html
  - http://openaccess.thecvf.com/content_cvpr_2014/html/Andriluka_2D_Human_Pose_2014_CVPR_paper.html
  README: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/shufflenetv2_mpii.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/shufflenetv2_mpii_256x256.py
  In Collection: shufflenetv2_mpii
  Metadata:
    Training Data: MPII
  Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--mpii--shufflenetv2_mpii_256x256
  Results:
  - Dataset: MPII
    Metrics:
      Mean: 0.828
      Mean@0.1: 0.205
    Task: Image-based Human Body 2D Pose Estimation
  Weights: https://download.openmmlab.com/mmpose/top_down/shufflenetv2/shufflenetv2_mpii_256x256-4fb9df2d_20200925.pth
