Collections:
- Metadata:
    Architecture:
    - SimpleBaseline2D
  Name: resnet_atrw
  Paper:
  - http://openaccess.thecvf.com/content_ECCV_2018/html/Bin_Xiao_Simple_Baselines_for_ECCV_2018_paper.html
  - https://arxiv.org/abs/1906.05586
  README: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/atrw/resnet_atrw.md
Models:
- Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/atrw/res50_atrw_256x256.py
  In Collection: resnet_atrw
  Metadata:
    Training Data: ATRW
  Name: animal--2d_kpt_sview_rgb_img--topdown_heatmap--atrw--res50_atrw_256x256
  Results:
  - Dataset: ATRW
    Metrics:
      AP: 0.9
      AP@0.5: 0.973
      AP@0.75: 0.932
      AR: 0.929
      AR@0.5: 0.985
    Task: 2D Animal Keypoint Detection
  Weights: https://download.openmmlab.com/mmpose/animal/resnet/res50_atrw_256x256-546c4594_20210414.pth
- Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/atrw/res101_atrw_256x256.py
  In Collection: resnet_atrw
  Metadata:
    Training Data: ATRW
  Name: animal--2d_kpt_sview_rgb_img--topdown_heatmap--atrw--res101_atrw_256x256
  Results:
  - Dataset: ATRW
    Metrics:
      AP: 0.898
      AP@0.5: 0.973
      AP@0.75: 0.936
      AR: 0.927
      AR@0.5: 0.985
    Task: 2D Animal Keypoint Detection
  Weights: https://download.openmmlab.com/mmpose/animal/resnet/res101_atrw_256x256-da93f371_20210414.pth
- Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/atrw/res152_atrw_256x256.py
  In Collection: resnet_atrw
  Metadata:
    Training Data: ATRW
  Name: animal--2d_kpt_sview_rgb_img--topdown_heatmap--atrw--res152_atrw_256x256
  Results:
  - Dataset: ATRW
    Metrics:
      AP: 0.896
      AP@0.5: 0.973
      AP@0.75: 0.931
      AR: 0.927
      AR@0.5: 0.985
    Task: 2D Animal Keypoint Detection
  Weights: https://download.openmmlab.com/mmpose/animal/resnet/res152_atrw_256x256-2bb8e162_20210414.pth
