Collections:
- Metadata:
    Architecture:
    - HRNetv2
    - DarkPose
  Name: hrnetv2_dark_wflw
  Paper:
  - https://ieeexplore.ieee.org/abstract/document/9052469/
  - http://openaccess.thecvf.com/content_CVPR_2020/html/Zhang_Distribution-Aware_Coordinate_Representation_for_Human_Pose_Estimation_CVPR_2020_paper.html
  - http://openaccess.thecvf.com/content_cvpr_2018/html/Wu_Look_at_Boundary_CVPR_2018_paper.html
  README: configs/face/2d_kpt_sview_rgb_img/topdown_heatmap/wflw/hrnetv2_dark_wflw.md
Models:
- Config: configs/face/2d_kpt_sview_rgb_img/topdown_heatmap/wflw/hrnetv2_w18_wflw_256x256_dark.py
  In Collection: hrnetv2_dark_wflw
  Metadata:
    Training Data: WFLW
  Name: face--2d_kpt_sview_rgb_img--topdown_heatmap--wflw--hrnetv2_w18_wflw_256x256_dark
  Results:
  - Dataset: WFLW
    Metrics:
      NME blur: 4.57
      NME expression: 4.3
      NME illumination: 3.96
      NME makeup: 3.87
      NME occlusion: 4.78
      NME pose: 6.99
      NME test: 3.98
    Task: 2D Face Landmark Detection
  Weights: https://download.openmmlab.com/mmpose/face/darkpose/hrnetv2_w18_wflw_256x256_dark-3f8e0c2c_20210125.pth
